### ISSUE TITLE
maxConcurrentCount Not working

### ISSUE THREAD

**Issue by angrymarker** [DalSoft/DalSoft.Hosting.BackgroundQueue#10] opened 2024-05-14 19:06 UTC
maxConcurrentCount set to 40. Deployed on a webfarm with 2 instances. only 2 tasks are running while the rest (are queued

**Comment by DalSoft** [comment] 2024-05-14 20:32
Let me take I look and confirm this is working as expected. Might need a bit more information on the tasks you are running.

**Comment by DalSoft** [comment] 2024-05-14 20:51
Ok just checked as I use this library myself and it seems to be ok with a simple task of sending emails concurrently.

The defaults though are `maxConcurrentCount:1` and `millisecondsToWaitBeforePickingUpTask:1000`

If you could share what you are doing that would be great.

A simple test would be to test it with a dummy task, that would rule out the task or the library.

**Comment by angrymarker** [comment] 2024-05-14 21:46
I'm using this tool as a way to "Fire and Forget" large running jobs that can take anywhere from 5 minutes to 20 hours.
Using Task.Run i had issues with the job randomly closing with no logged exception. Found out it was the apppool recycle causing the issue so I downloaded this library.

I have this app deployed on 2 servers - chwf3a & chwf3b, and funnily enough, only 2 jobs seem to run. 

When I run the jobs, I assign a database id so I can view job progress. The initial status is "Starting". Once queued, becomes "Beginning Preflight", until finished, "Preflight Complete".
I have 1 job set as "Preflight Complete", 2 jobs set as "Beginning Preflight", and 5 set as "Starting", telling me they haven't queued yet
Startup.cs
```
 public void ConfigureServices(IServiceCollection services)
 {
    ...
    services.AddBackgroundQueue(maxConcurrentCount: 40, millisecondsToWaitBeforePickingUpTask: 1000,
              onException: exception =>
              {
                  //logexception
              });
}
```
PreflightController
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using WebApplication1.Models;
using WebApplication1.Interact;
using System.Collections.Generic;
using WebApplication1.Models.DPX;
using DalSoft.Hosting.BackgroundQueue;

namespace WebApplication1.Controllers
{
   
    [ApiController]
    [Route("dpx/[controller]")]
    [System.Runtime.Versioning.SupportedOSPlatform("windows")]
    public class PreflightController : ControllerBase
    {
        
        private readonly ILogger<PreflightController> _logger;
        private readonly BackgroundQueue _backgroundQueue;

       
        public PreflightController(ILogger<PreflightController> logger, BackgroundQueue backgroundQueue)
        {
            _logger = logger;
            _backgroundQueue = backgroundQueue;
        }

       
        [HttpPost]
        public ActionResult<int> Post( [FromBody] CRAData runData)
        {
             //Log the start of the job
             int runID = PTADB.startAsyncJob(runData, "Starting");
            _backgroundQueue.Enqueue(async (cancellationToken) =>
                PTADB.updateRun(runID, "Beginning Preflight");
                //Sends an api POST call to another server, and waits until the application is complete
                //This can take anywhere from 30 seconds to 20 hours, depending on how many records are inputted
                 IgniteAPI.runPreflight(runData, runID);
                 PTADB.endAsyncJob(runID, "Preflight Complete");
            });
           //return id so user can query status
           return runID;
        }
    }
}
```

**Comment by bergy6808** [comment] 2024-08-19 18:54
I have the same issue. I just checked the code and BackgroundQueueService.ExecuteAsync seems to await each task one at the time. So the maxConcurrentCount parameter is not really used.. Instead BackgroundQueueService.ExecuteAsync could create a Timer that periodically Dequeue the maximum amount of tasks and awaits them in an async void handler (protected by try-catch). I can make a pull request if you want ?

**Comment by DalSoft** [comment] 2024-09-01 00:31
Apologies for the delayed response—I’ve been on holiday. Thank you for offering to submit a PR. I’ve been meaning to get organized with my side projects for a while, and [finally got some time this weekend](https://dalsoft.co.uk/blog/too-many-side-projects/) to do so.

I have now confirmed and resolved the issue, and I’ve added tests to verify that it is running more than one task concurrently. The new package release will be pushed to NuGet on Monday, and I’ll close this issue afterward.

**Comment by DalSoft** [comment] 2024-09-03 01:37
This has now been fixed and tested https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/commit/ef1c383f593c3955e6812a05e36efce0a21a423a 

[Package](https://www.nuget.org/packages/DalSoft.Hosting.BackgroundQueue)

Sorry for the delay in getting this resolved.

**Comment by bergy6808** [comment] 2024-09-03 16:24
Thank you for the modifications. It's better. But there is still an issue. If a single background task takes forever to complete, it will block the whole queue forever. I suggest using a Timer (System.Threading.Timer) instead to await tasks (async void, with a try catch to be safe). And keep the while loop, with the cancellation token. And dispose the Timer properly if task is cancelled. That's how I see it.

**Comment by DalSoft** [comment] 2024-09-05 00:42
Your 100% right using a Timer is the best way to do this 👍

There are two implementations I've done.

 [v1.1.1](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/compare/v1.1.0...v1.1.1) this uses [System.Timers.Timer](https://learn.microsoft.com/en-us/dotnet/api/system.timers.timer) and targets netstandard2.0, works with .NET Core 2.0 and above.
 
 [v2.0.0](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/compare/v1.1.1...v2.0.0) this uses [System.Threading.PeriodicTimer](https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer), which is a much better fit for background tasks. v2.0 targets net6.0 and works with .NET 6.0 and above.

The reason for v2.0 changing the targeting to net6.0 is that it's a lot easier to support Dependency Injection, which is fully supported in v2.0 using a service scope per queue item. I want to support scheduled Jobs in the future, and this will be easier to implement using a new version of .NET. Lastly it's nicer for me to use modern C# language features.

v2.0 has a [fully working example in the repo](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/tree/master/DalSoft.Hosting.BackgroundQueue.Examples.WebApi) using Swagger if you hit `POST /backgroundtasks`, then keep hitting `GET /backgroundtasks` you can see tasks being processed in to queue up to the maxConcurrentCount, with millisecondsToWaitBeforePickingUpTask being used to throttle access to the queue, which was my original vision for the package.

Thanks for your patience and advice for improving the package.

**Comment by bergy6808** [comment] 2024-09-05 21:08
Thank you for working on it so fast! I just checked your two implementations using timers.

### For the 1.1.1 version
That's what I had in mind, except that 

1. The _backgroundQueue.Dequeue is not currently awaited. I am no async expert, but I think it's best if the callback is async (`timer.Elapsed += async (sender, args) =>` and `await _backgroundQueue.Dequeue(..)`). A task not awaited has no guaranty to finish, as I read somewhere. 
2. I think there's a maximum of one execution per Timer tick if I read your code correctly? I liked the little while loop with the Task.WhenAll in the 1.1.0. I understand it might be your vision for the package, but I don't think the user really needs to choose a throttle speed. I think the simple maxConcurrentCount is enough. What I had in mind reading the name MillisecondsToWaitBeforePickingUpTask , was a minimal delay before picking up any task, ensuring it would not be executed too soon. 

### For the 2.0.0 version
Same two issues. But simply awaiting it would mean that we're back with the older issues I mentioned, as the the PeriodicTimer seems to not allow concurrent executions of the 'callback' by design.

**Comment by DalSoft** [comment] 2024-09-05 23:42
Thanks for taking the time to review my code, some notes from me:

**Point 1:** 

My understanding is a Task not awaited has no Continuation, so [if an exception occurs it is swallowed](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014), which is why you get a compiler warning. For that we have onException, which handles exceptions in the Task. You can test this with the [example project](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/tree/master/DalSoft.Hosting.BackgroundQueue.Examples.WebApi)  

The only way I've triggered any problem is Mocking the CreateAsyncScope() call (as it's not in the try catch block) and forcing an exception. [This is unlikely to happen in the wild](https://andrewlock.net/exploring-dotnet-6-part-10-new-dependency-injection-features-in-dotnet-6/), and why I went with net6.0.

I think people saying a a task not awaited has no guaranty to finish, comes back to not awaiting tasks in say a ASP.NET controller. What they really mean it's not guaranteed to finish **before** the parent Task i.e. the request completes, or the even before the server process is shutdown. This is why in many fire and forget code examples people get a `System.ObjectDisposedException`, because the request Task already disposed the service.

We don't have that problem because the Dequeue Task is a nested Task of [BackgroundService.ExceuteAsync]( https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0&tabs=visual-studio) (+ we scope service DI per run). BackgroundService controls the Task lifecycle with it's linked cancellation token, which is passed to the user's Task. So in a way not guaranteed to finish, but user knows the BackgroundService is shutting down, and can pass the cancellation token to all their awaits.

I've forgotten a lot of my understanding of .NET internals, as it doesn't come up very often, [this is a good write up I read today](https://medium.com/net-under-the-hood/internal-mechanisms-of-tasks-in-net-ef461956d4a7).  One improvement that might be worth investigating is allowing the user to provide TaskCreationOptions for their Task, but not sure if it's micro optimization.

**Point 2**:

You have me thinking about this now. 

The main use case for this package is a drop in replacement for [HostingEnvironment.QueueBackgroundWorkItem](https://www.hanselman.com/blog/HowToRunBackgroundTasksInASPNET.aspx) i.e. safely sending an email in the background. All versions tick that box ✔.

I think you're right about maxConcurrentCount being enough. At the time I developed the package I was migrating legacy code (hence needing a drop in replacement for QueueBackgroundWorkItem) and the servers were flaky, so I was being ultra cautious.

Think we can set the default value of MillisecondsToWaitBeforePickingUpTask to something more sensible than a second,  and allow users to set the value to < 500ms which they can't ATM.

**Comment by DalSoft** [comment] 2024-09-06 00:14
I can confirm setting the default value of MillisecondsToWaitBeforePickingUpTask to 10ms seems optimum. Now it works by default as most people expect allowing concurrent tasks up to the maxConcurrentCount limit. 

Users still have the option if they need to warm 🔥 up a old IBM server before allowing concurrency, by setting MillisecondsToWaitBeforePickingUpTask to a higher value.

![image](https://github.com/user-attachments/assets/c0018a07-9a64-43d0-8068-6b13ae4a0bea)

**Comment by bergy6808** [comment] 2024-09-06 17:06
Alright! Thanks for the info. Everything seems good to me then.

**Comment by DalSoft** [comment] 2024-09-12 00:58
I've just released **v2** of the package! You can check it out here: [v2.0.0...v2.0.1](https://github.com/DalSoft/DalSoft.Hosting.BackgroundQueue/compare/v2.0.0...v2.0.1) | [Package](https://www.nuget.org/packages/DalSoft.Hosting.BackgroundQueue/2.0.1)

In this release, I set the default `MillisecondsToWaitBeforePickingUpTask` to 10ms. I've tested it in my production environments over the past week, and I'm happy to report that it's stable and performing well.

While a failure in `CreateAsyncScope()` is highly unlikely, I wrote a test to force an exception in the `CreateAsyncScope` call and found that `onException` wasn’t being triggered. I’ve fixed this issue, so now if **anything** fails within a task, `onException` will be called.

Additionally, I've increased the test coverage for the package.

I want to give a big thanks to both @bergy6808 and @angrymarker for your contributions. Your feedback reignited my motivation to improve this package 😎. Thanks to your input, the background service now supports concurrency and handles more advanced scenarios, beyond just being a replacement for `HostingEnvironment.QueueBackgroundWorkItem`.

**Closed as completed by DalSoft** 2024-09-12 00:58 UTC
